# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntranetMall' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IntranetMall



#view components
#pod 'BALoadingView'
pod 'MBProgressHUD', '~> 0.8'
pod 'ActionSheetPicker-3.0'
pod 'JASidePanels', '~> 1.3'
pod 'SMPageControl', '~> 1.2'
pod 'YAScrollSegmentControl', '~> 0.1'
pod 'ZFDragableModalTransition'
pod 'VMaskTextField', '~> 1.0'
pod 'ASJDropDownMenu', '~> 1.1'
pod 'QRCodeReaderViewController', '~> 4.0'
pod 'ZRQRCodeViewController', '~> 3.1'
pod 'TTTAttributedLabel', '~> 2.0'

pod 'Fabric'
pod 'Crashlytics'
pod 'RNCryptor-objc', '~> 3.0'


#camera
pod 'MWPhotoBrowser', '~> 2.1'

#connection
pod 'AFNetworking', '~> 2.0'
pod 'AWSSNS', '~> 2.3'
#pod 'Reachability', '~> 3.2'


#productivity
pod 'CocoaLumberjack', '~> 1.9'
pod 'HexColors', '~> 2.2'
pod 'UIImage+PDF', '~> 1.1'
pod 'SDWebImage'
pod 'ObjectiveRecord', '~> 1.5'
pod 'DateTools', '~> 1.5'

#helper pods
pod 'NSStringMask'


#enhancement pods
pod 'TPKeyboardAvoiding'


end

target 'IntranetMallDev' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IntranetMallDev

#view components
#pod 'BALoadingView'
pod 'MBProgressHUD', '~> 0.8'
pod 'ActionSheetPicker-3.0'
pod 'JASidePanels', '~> 1.3'
pod 'SMPageControl', '~> 1.2'
pod 'YAScrollSegmentControl', '~> 0.1'
pod 'ZFDragableModalTransition'
pod 'VMaskTextField', '~> 1.0'
pod 'ASJDropDownMenu', '~> 1.1'
pod 'QRCodeReaderViewController', '~> 4.0'
pod 'ZRQRCodeViewController', '~> 3.1'
pod 'TTTAttributedLabel', '~> 2.0'

pod 'Fabric'
pod 'Crashlytics'
pod 'RNCryptor-objc', '~> 3.0'


#camera
pod 'MWPhotoBrowser', '~> 2.1'

#connection
pod 'AFNetworking', '~> 2.0'
pod 'AWSSNS', '~> 2.3'
#pod 'Reachability', '~> 3.2'


#productivity
pod 'CocoaLumberjack', '~> 1.9'
pod 'HexColors', '~> 2.2'
pod 'UIImage+PDF', '~> 1.1'
pod 'SDWebImage'
pod 'ObjectiveRecord', '~> 1.5'
pod 'DateTools', '~> 1.5'

#helper pods
pod 'NSStringMask'


#enhancement pods
pod 'TPKeyboardAvoiding'

end

target 'IntranetMallHom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IntranetMallHom


#view components
#pod 'BALoadingView'
pod 'MBProgressHUD', '~> 0.8'
pod 'ActionSheetPicker-3.0'
pod 'JASidePanels', '~> 1.3'
pod 'SMPageControl', '~> 1.2'
pod 'YAScrollSegmentControl', '~> 0.1'
pod 'ZFDragableModalTransition'
pod 'VMaskTextField', '~> 1.0'
pod 'ASJDropDownMenu', '~> 1.1'
pod 'QRCodeReaderViewController', '~> 4.0'
pod 'ZRQRCodeViewController', '~> 3.1'
pod 'TTTAttributedLabel', '~> 2.0'

pod 'Fabric'
pod 'Crashlytics'
pod 'RNCryptor-objc', '~> 3.0'



#camera
pod 'MWPhotoBrowser', '~> 2.1'

#connection
pod 'AFNetworking', '~> 2.0'
pod 'AWSSNS', '~> 2.3'
#pod 'Reachability', '~> 3.2'


#productivity
pod 'CocoaLumberjack', '~> 1.9'
pod 'HexColors', '~> 2.2'
pod 'UIImage+PDF', '~> 1.1'
pod 'SDWebImage'
pod 'ObjectiveRecord', '~> 1.5'
pod 'DateTools', '~> 1.5'

#helper pods
pod 'NSStringMask'


#enhancement pods
pod 'TPKeyboardAvoiding'

end
